import React, { useEffect } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Script from 'next/script';

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div id="hero">
          <canvas id="hero-lightpass"/>
        </div>
        <div className="intro">
          <h1>The New Dev Ed Pro</h1>
          <video src="/video/Apple-Dev Ed Pro.mp4"></video>
        </div>
        <section>
          <h1>REVOLUTIONARRY</h1>
        </section>
      </main>
    <Script
      src="/js/ScrollMagic.min.js"
    ></Script>
    <Script
      src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.7/plugins/animation.gsap.js"
      integrity="sha256-peenofh8a9TIqKdPKIeQE7mJvuwh+J0To7nslvpj1jI="
      crossorigin="anonymous"
    ></Script>
    <Script
      src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.7/plugins/debug.addIndicators.js"
      integrity="sha256-31FC/OT6XpfjAhj9FuXjw5/wPXXawCAjJQ29E23/XPk="
      crossorigin="anonymous"
    ></Script>
    <Script
      src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.3/TweenMax.min.js"
      integrity="sha256-lPE3wjN2a7ABWHbGz7+MKBJaykyzqCbU96BJWjio86U="
      crossorigin="anonymous"
    ></Script>
      <Script src="/js/script.js"></Script>
    </div>
  )
}
